name: Publish OCI Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: container-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: steam-remote-docker
  IMAGE_TAGS: latest sha-${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  publish:
    name: Build and publish linux/amd64
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build OCI image with Buildah
        id: build
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./build/container/Containerfile
          context: .
          platforms: linux/amd64
          build-args: |
            VCS_REF=${{ github.sha }}
          oci: true
          layers: true

      - name: Push image with Podman
        id: push
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
